### ISSUE TITLE
Implement Support for SHIFT + Tab

### ISSUE THREAD

**Issue by scott-fisher-iii** [wakirin/litepicker-module-navkeyboard#2]
**Problem:**
Typical keyboard shortcuts are `TAB` to move forward and `SHIFT + TAB` to move backward.

If you press `SHIFT + TAB` it just moves forward through the selectable items.

**Expected:**
Pressing `SHIFT + TAB` will rotate through the items in reverse order.

**Related:**
I can enter another bug as well, but I can't seem to get back to the header (e.g. Month/Year dropdowns, Month arrows) once I get into the date selection section.
Adding `SHIFT + TAB` to get from the date selection back to the header would likely solve this.

**Comment by wakirin** [comment]
added in v0.1.1

**Comment by scott-fisher-iii** [comment]
I've played around with this a little and it seems to be working. Thanks for the quick turnaround!
