### ISSUE TITLE
Tabbing to Disabled Dates

### ISSUE THREAD

**Issue by scott-fisher-iii** [wakirin/litepicker-module-navkeyboard#3]
If you have a disabled date (i.e. less than the minimum date value), then it is still reachable by tab.

Expected:
If a date is disabled, then it should not be reachable by pressing the tab (or shift-tab) key.

Fiddle:
https://jsfiddle.net/qosc201v/1/

**Comment by wakirin** [comment]
fixed in v0.2.1

**Comment by scott-fisher-iii** [comment]
Tested and confirmed in JSFiddle with Litepicker v1.4.7 and Litepicker-module-naykeyboard v.0.2.1
