### ISSUE TITLE
Unable to Tab to Dropdowns

### ISSUE THREAD

**Issue by scott-fisher-iii** [wakirin/litepicker-module-navkeyboard#4]
**Problem:**
When the month/year dropdowns are enabled, I am unable to access them via the tab key on the keyboard.

**Setup:**
<pre>new Litepicker({
	element: document.getElementById('datepicker'),
  dropdowns: {
    minYear: new Date().getFullYear() - 100,
    maxYear: new Date().getFullYear() + 20,
    months: true,
    years: true
  },	
  moduleNavKeyboard: true
})</pre>

**Expected:**
I should be able to reach the dropdown menus via the keyboard (pressing Tab).

Fiddle:
https://jsfiddle.net/qosc201v/3/

**Comment by wakirin** [comment]
fixed in v0.2.1

**Comment by scott-fisher-iii** [comment]
Tested and confirmed in JSFiddle with Litepicker v1.4.7 and Litepicker-module-naykeyboard v.0.2.1
